prepare_data.py:
  debug_mode: false
  tasks:
    determine_roads_surfaces: true
    determine_restricted_AOI: true
  input:
    input_folder: /mnt/data-01/gsalamin/proj-roadsurf-b/02_Data
    input_files:
      roads: /initial/TLM/Strassen/corrected_roads_inside_AOI.shp
      roads_param: /initial/TLM/Strassen/Objektarten_to_keep.xlsx
      forests: /initial/TLM/Clip_Wald_Bodenbedeckung/forests.shp
      aoi: /initial/AOI/temp_AOI_Prototyp_Belagsarten_2tiles.shp
  output_folder: /mnt/data-01/gsalamin/proj-roadsurf-b/02_Data/processed


prepare_data_od.py:
  debug_mode: false
  tasks:
    determine_roads_surfaces: true
    generate_tiles_info: false
    generate_labels: true
  input:
    input_folder: /mnt/data-01/gsalamin/proj-roadsurf-b/02_Data/initial
    input_files:
      roads: /TLM/Strassen/corrected_roads_inside_AOI.shp
      roads_param: /TLM/Strassen/Objektarten_to_keep.xlsx
      forests: /TLM/Clip_Wald_Bodenbedeckung/forests.shp
      aoi: /AOI/temp_AOI_Prototyp_Belagsarten_2tiles.shp
  output_folder: /mnt/data-01/gsalamin/proj-roadsurf-b/02_Data/processed
  # ok_tiles: /tables/ok_tiles_z18.xlsx
  zoom_level: 18  # keep between 17 and 20  


correct_gt.py:
  input:
    input_folder: /mnt/data-01/gsalamin/proj-roadsurf-b/02_Data
    input_files:
      initial_roads: /initial/TLM/Strassen/Roads_inside_AOI.shp
      corrections: /initial/TLM/Strassen/test_natural_roads_feedback.shp


RS_images_to_S3.py:
  access_key: ...
  secret_key: ...
  url: https://s3.pub1.infomaniak.cloud
  datapath: D:\Export_RS\*
  bucket: proj-roadsurf
  outpath: 02_Data/initial/images_RS/


statistical_analysis.py:
  debug_mode: false
  use_zonal_stats: false
  correct_balance: false
  processed:
    processed_folder: /mnt/data-01/gsalamin/proj-roadsurf-b/02_Data/processed
    input_files:
      images: /obj_detector/all-images
      roads: /shapefiles_gpkg/roads_polygons.shp
      tiles: /json/tiles_aoi_z18.geojson
  final_folder: /mnt/data-01/gsalamin/proj-roadsurf-b/02_Data/final
  param:
    pixel_threshold: 10
    max_confidence: 12.5
    make_boxplots: true
    do_ks_test: false
    make_pca: true


limit_visible_aoi.py:
  data_folder: /mnt/data-01/gsalamin/proj-roadsurf-b/02_Data
  input:
    images: processed/obj_detector/all-images
    roads: processed/shapefiles_gpkg/roads_for_OD.shp
    roads_param: initial/TLM/Strassen/Objektarten_to_keep.xlsx
    ground_truth: processed/json/ground_truth_labels.geojson
  output:
    images: processed/obj_detector/all-images-limited-aoi
  zoom: 18


final_metrics.py:
  debug_mode: True
  threshold: 0
  initial_folder: /mnt/data-01/gsalamin/proj-roadsurf-b/02_Data/initial
  processed_folder: /mnt/data-01/gsalamin/proj-roadsurf-b/02_Data/processed
  object_detector_folder: obj_detector
  final_folder: /mnt/data-01/gsalamin/proj-roadsurf-b/02_Data/final
  input:
    ground_truth: json/ground_truth_labels.geojson
    to_evaluate:
      trn: trn_predictions.geojson
      val: val_predictions.geojson
      tst: tst_predictions.geojson
      # oth: oth_predictions.geojson 
