prepare_data.py:
  debug_mode: False
  tasks:
    determine_roads_surfaces: True
    determine_restricted_AOI: True
    generate_tiles_info: True
  input:
    input_folder: /mnt/data-01/gsalamin/proj-roadsurf-b/02_Data
    input_files:
      roads: /initial/TLM/Strassen/Roads_inside_AOI.shp
      roads_param: /initial/TLM/Strassen/Objektarten_to_keep.xlsx
      forests: /initial/TLM/Clip_Wald_Bodenbedeckung/forests.shp
      aoi: /initial/AOI/temp_AOI_Prototyp_Belagsarten_2tiles.shp
  output_folder: /mnt/data-01/gsalamin/proj-roadsurf-b/02_Data/processed
  zoom_level: 17  # keep between 17 and 20  


RS_images_to_S3.py:
  access_key: ...
  secret_key: ...
  url: https://s3.pub1.infomaniak.cloud
  datapath: D:\Export_RS\*
  bucket: proj-roadsurf
  outpath: 02_Data/initial/images_RS/


generate_tilesets.py:
  debug_mode: False
  datasets:
    aoi_tiles_geojson: /mnt/data-01/gsalamin/proj-roadsurf-b/02_Data/processed/json/tiles_aoi.geojson
    orthophotos_web_service:
      type: XYZ      # supported values: 1. MIL = Map Image Layer 2. WMS 3. XYZ
      url: https://titiler.vm-gpu-01.stdl.ch/mosaicjson/tiles/{z}/{x}/{y}.tif?url=/data/mosaic_3857.json&bidx=2&bidx=3&bidx=4&bidx=1&no_data=0&return_mask=false&pixel_selection=lowest
      srs: "EPSG:3857"
      # parameters:
      #   url: /data/mosaic_3857.json
      #   no_data: 0
      #   return_mask: false
      #   pixel_selection: lowest
  output_folder: /mnt/data-01/gsalamin/proj-roadsurf-b/02_Data/processed/obj_detector
  tile_size: 256 # per side, in pixels
  overwrite: False
  n_jobs: 10
  COCO_metadata:
    year: 2018
    version: 1.0
    description: TLM3D, Roads layer
    contributor: swisstopo
    url: https://swisstopo.ch
    license:
      name: unknown
      url: https://www.swisstopo.admin.ch/fr/home/meta/conditions-generales/geodonnees/ogd.html
    category:
      name: 'road'
      supercategory: 'facility'


statistical_analysis.py:
  debug_mode: False
  use_zonal_stats: False
  correct_balance: True
  processed:
    processed_folder: /mnt/data-01/gsalamin/proj-roadsurf-b/02_Data/processed
    input_files:
      images: /obj_detector/all-images
      roads: /shapefiles_gpkg/roads_polygons.shp
      tiles: /json/tiles_aoi.geojson
  final_folder: /mnt/data-01/gsalamin/proj-roadsurf-b/02_Data/final
  param:
    threshold: 50