prepare_data.py:
  tasks:
    determine_roads_surfaces: False
    determine_restricted_AOI: False
    make_raster_mosaic: False
    generate_tiles_json: True
  input:
    input_folder: /mnt/data-01/gsalamin/proj-roadsurf-b/02_Data
    input_files:
      roads: /initial/TLM/Strassen/Roads_inside_AOI.shp
      roads_param: /initial/TLM/Strassen/Objektarten_to_keep.xlsx
      forests: /initial/TLM/Clip_Wald_Bodenbedeckung/forests.shp
      aoi: /initial/AOI/AOI_Prototyp_Belagsarten.shp
  output:
    output_folder: /mnt/data-01/gsalamin/proj-roadsurf-b/02_Data/processed
    output_files:
      roads: /shapefiles_gpkg/non_forest_wide_roads.shp
      restricted_AOI: /shapefiles_gpkg/restricted_AOI.shp
      tiles_aoi:  /json/tiles_aoi.geojson
      gpkg_tiles: /shapefiles_gpkg/epsg3857_tiles.gpkg
  param_tiles:
    zoom_level: 18
      
generate_training_sets.py:
  debug_mode: True
  datasets:
    aoi_tiles_geojson: /mnt/data-01/gsalamin/proj-roadsurf-b/02_Data/processed/json/tiles.geojson
    ground_truth_labels_geojson: /mnt/data-01/gsalamin/proj-roadsurf-b/02_Data/processed/shapefiles/non_forest_wide_roads.shp
    orthophotos_web_service:
      type: WMTS      # supported values: 1. MIL = Map Image Layer 2. WMS 3. WMTS
      url: https://titiler.vm-gpu-01.stdl.ch/mosaicjson/tiles
      layers: /data/mosaic.json
      srs: "EPSG:3857"
      no_data: 0
  output_folder: /mnt/data-01/gsalamin/proj-roadsurf-b/02_Data/processed/
  tile_size: 256 # per side, in pixels
  overwrite: False
  n_jobs: 10
  COCO_metadata:
    year: 2018
    version: 1.0
    description: TLM3D, Roads layer
    contributor: swisstopo
    url: https://swisstopo.ch
    license:
      name: unknown
      url: https://www.swisstopo.admin.ch/fr/home/meta/conditions-generales/geodonnees/ogd.html

wmts-geoquery.py:
  debug: True
  url: https://wmts.geo.admin.ch/EPSG/2056/1.0.0/WMTSCapabilities.xml
  layer: ch.swisstopo.swissimage-product
  tiles: 02_Data/processed/json/tiles_aoi.geojson
  width: 100000
  time: '2018'
  tmp: 02_Data/processed/images
