# Procedure based on a supervised classification

prepare_data.py:
  debug_mode: false
  tasks:
    determine_roads_surfaces: true
    determine_restricted_AOI: true
  input:
    input_folder: data
    input_files:
      roads: swissTLM3D/roads_lines.shp
      roads_param: roads_parameters.xlsx
      forests: swissTLM3D/forests.shp
      aoi: AOI/aoi.shp
  output_folder: outputs

prepare_data_od.py:
  tasks:
    determine_roads_surfaces: false
    generate_tiles_info: true
    generate_labels: false
  input:
    input_folder: data
    input_files:
      roads_param: roads_parameters.xlsx
      aoi: AOI/aoi.shp
  processed_input:
    roads_for_labels: roads_polygons_stats.shp
  output_folder: outputs
  zoom_level: 18  # keep between 17 and 20  

generate_tilesets.py:
  debug_mode: false
  datasets:
    aoi_tiles_geojson: outputs/json_inputs/tiles_aoi.geojson
    orthophotos_web_service:
      type: XYZ
      url: https://titiler.vm-gpu-01.stdl.ch/mosaicjson/tiles/{z}/{x}/{y}.tif?url=/data/mosaic_3857.json&bidx=2&bidx=3&bidx=4&bidx=1&no_data=0&return_mask=false&pixel_selection=lowest
      srs: "EPSG:3857"
  output_folder: outputs/obj_detector
  tile_size: 256 # per side, in pixels
  overwrite: False
  n_jobs: 10

statistical_analysis.py:
  debug_mode: true
  use_zonal_stats: false
  correct_balance: false
  processed:
    processed_folder: outputs
    input_files:
      images: obj_detector/all-images
      roads: shapefiles_gpkg/roads_polygons_stats.shp
      tiles: json_inputs/tiles_aoi.geojson
  final_folder: outputs/final
  param:
    pixel_threshold: 10
    max_margin_of_interest: 12.5
    make_boxplots: true
    do_ks_test: false
    make_pca: true